<?php
$acomodacoes = array(
    array(
        'id' => 1,
        'titulo' => 'Suíte master',
        'descricao' => array(
            'Cama de casal Queen',
            'Frigobar',
            'Varanda com vista pro mar',
            'Banheiro individual',
        ),
        'fotoPrincipal' => $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-1.png',
        'fotos' => array(
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-1.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-2.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-3.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-4.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-5.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-6.png',
        ),
    ),
    array(
        'id' => 2,
        'titulo' => 'Suíte simples',
        'descricao' => array(
            'Acomodação para duas pessoas ou 1 pessoa (quarto individual)',
            'Cama de casal Queen',
            'Frigobar',
            'Banheiro individual',
        ),
        'fotoPrincipal' => $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-2.png',
        'fotos' => array(
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-2.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-1.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-3.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-4.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-5.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-6.png',
        ),
    ),
    array(
        'id' => 3,
        'titulo' => 'Quarto coletivo com 3 beliches',
        'descricao' => array(
            'Acomodação coletiva para até 6 pessoas',
            '3 beliches',
            'Frigobar',
            'Locker no quarto com 1 armazenamento para cada pessoa',
        ),
        'fotoPrincipal' => $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-3.png',
        'fotos' => array(
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-3.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-1.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-2.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-4.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-5.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-6.png',
        ),
    ),
    array(
        'id' => 4,
        'titulo' => 'Quarto coletivo feminino com 3 beliches',
        'descricao' => array(
            'Acomodação coletiva de até 6 pessoas',
            '3 beliches',
            'Frigobar',
            'Locker no quarto com 1 armazenamento para cada pessoa',
            'Banheiro coletivo no quarto com 1 sanitário privativo',
            '1 chuveiro com vestiário',
        ),
        'fotoPrincipal' => $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-4.png',
        'fotos' => array(
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-4.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-1.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-2.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-3.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-5.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-6.png',
        ),
    ),
    array(
        'id' => 5,
        'titulo' => 'Quarto de coletivo com acessibilidade',
        'descricao' => array(
            'Acomodação coletiva de até 6 pessoas',
            '3 beliches',
            'Frigobar',
            'Locker no quarto com 1 armazenamento para cada pessoa',
            'Banheiro coletivo no quarto com 1 sanitário e chuveiro com acessibilidade para deficiente',
            '1 chuveiro coletivo sem acessibilidade',
            '1 sanitário privativo com porta',
        ),
        'fotoPrincipal' => $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-5.png',
        'fotos' => array(
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-5.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-1.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-2.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-3.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-4.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-6.png',
        ),
    ),
    array(
        'id' => 6,
        'titulo' => 'Quarto coletivo com 4 beliches',
        'descricao' => array(
            'Acomodação coletiva para até 8 pessoas',
            '4 beliches',
            'Frigobar',
            'Locker no quarto com 1 armazenamento para cada pessoa',
        ),
        'fotoPrincipal' => $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-6.png',
        'fotos' => array(
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-6.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-1.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-2.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-3.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-4.png',
            $GLOBALS['home_url'] . '/public/img/acomodacoes/acomodacao-5.png',
        ),
        'observacao' => 'No caso dos quartos coletivos com 3 e 4 beliches ambos terão 1 banheiro coletivo entre os dois para uso de ambos, segue descrição do banheiro:',
        'lista-titulo' => 'Banheiro coletivo (dois banheiros coletivos, hum para cada 2 quartos):',
        'lista' => array(
            '2 chuveiros com vestiários embutidos',
            '1 sanitário privativo com porta',
            '1 pia dupla com espelho',
            '1 mictório',
        ),
    ),
);
